### ISSUE TITLE
Clone error when grouping actions

### ISSUE THREAD

**Issue by egerpe-ats** [Romainlg29/use-broadcast#7]
In my Zustand store I have all the actions grouped together like this (I got the idea from this blog post: [https://tkdodo.eu/blog/working-with-zustand#separate-actions-from-state](https://tkdodo.eu/blog/working-with-zustand#separate-actions-from-state))
```typescript
const useBearStore = create((set) => ({
  bears: 0,
  fish: 0,
  actions: {
    increasePopulation: (by) => set((state) => ({ bears: state.bears + by })),
    eatFish: () => set((state) => ({ fish: state.fish - 1 })),
    removeAllBears: () => set({ bears: 0 }),
  },
}))
```

But this approach results in a clone error when trying to share the store between tabs. I'm guessing that's because the `actions` object contains functions, that can't be send as mentioned on the docs.
So to make it work I have to flatten my store so the actions are on the same level as the state, like this:
```typescript
const useBearStore = create((set) => ({
  bears: 0,
  fish: 0,
  increasePopulation: (by) => set((state) => ({ bears: state.bears + by })),
  eatFish: () => set((state) => ({ fish: state.fish - 1 })),
  removeAllBears: () => set({ bears: 0 }),
}))
```

Is there any way to keep my original structure that doesn't error?

**Comment by Romainlg29** [comment]
Hi @egerpe-ats ,

Currently not.

As mentioned in the docs, the Broadcast Channel API use the structuredClone function under the hood.
You're getting this error, because the shared(store) only check and ignore functions that are at the object root and not nested.

Maybe, I can check if I can add an option for that but it's going to slow the sync process if you've a lot of objects.

**Comment by egerpe-ats** [comment]
Thanks for your reply! Don't worry, I'll just flatten the structure, it's not a big deal.
